name: oOf dynamic again

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://download.c.realme.com/osupdate/RMX2185_11_OTA_0790_all_dsysIPFhgWAX.ozip
  ROM_NAME: Realme-RMX2185
  PRODUCT_IMAGE: false
  OPPRODUCT_IMAGE: false
  WHOLE_VENDOR: false
  Codename:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get update -y
            sudo apt-get install -y simg2img 
            sudo apt-get install zip gzip tar
            sudo -E apt-get install expect
            sudo pip3 install --upgrade setuptools
            sudo pip3 install --upgrade pip
            sudo apt update 2>/dev/null | grep packages
        
       - name: Making
         run: |
              git clone https://github.com/rui-ports/TWRP-device-tree-generator
              sudo chmod +x TWRP-device-tree-generator
              cd TWRP-device-tree-generator
              sudo ./start.sh --cli
             
